# Generated by Django 5.0 on 2024-01-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
